'Ahorn.FriendlyCaptcha:OverrideConfigurationMixin':
  abstract: true
  ui:
    inspector:
      tabs:
        friendlyCaptcha:
          label: 'Friendly Captcha'
          icon: 'resource://Ahorn.FriendlyCaptcha/Icons/frc-icon.svg'
          position: 15
      groups:
        config:
          label: i18n
          icon: 'resource://Ahorn.FriendlyCaptcha/Icons/frc-icon.svg'
          tab: friendlyCaptcha
  properties:
    overrideOptions:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        inspector:
          group: config
    overrideStartVerification:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideOptions ? false : true'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: i18n
            allowEmpty: true
            multiple: false
            values:
              auto:
                label: 'Auto'
              focus:
                label: 'Focus'
              none:
                label: 'None'
    overrideLanguage:
      type: string
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideOptions ? false : true'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: i18n
            allowEmpty: true
            multiple: false
            values:
              'en':
                  label: i18n
              'de':
                label: i18n
              'nl':
                label: i18n
              'fr':
                label: i18n
              'it':
                label: i18n
              'pt':
                label: i18n
              'es':
                label: i18n
              'ca':
                label: i18n
              'ja':
                label: i18n
              'da':
                label: i18n
              'ru':
                label: i18n
              'sv':
                label: i18n
              'tr':
                label: i18n
              'el':
                label: i18n
              'uk':
                label: i18n
              'bg':
                label: i18n
              'cs':
                label: i18n
              'sk':
                label: i18n
              'no':
                label: i18n
              'fi':
                label: i18n
              'lv':
                label: i18n
              'lt':
                label: i18n
              'pl':
                label: i18n
              'et':
                label: i18n
              'hr':
                label: i18n
              'sr':
                label: i18n
              'sl':
                label: i18n
              'hu':
                label: i18n
              'ro':
                label: i18n
              'zh':
                label: i18n
    overrideKeys:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        inspector:
          group: config
    overrideSiteKey:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideKeys ? false : true'
    overrideApiKey:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideKeys ? false : true'
    overrideApiEndpoint:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideOptions ? false : true'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: i18n
            allowEmpty: true
            multiple: false
            values:
              'global':
                label: i18n
              'eu':
                label: i18n
    overrideTheme:
      type: string
      ui:
        label: i18n
        inspector:
          group: config
          hidden: 'ClientEval:node.properties.overrideOptions ? false : true'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'
          editorOptions:
            placeholder: i18n
            allowEmpty: true
            multiple: false
            values:
              'auto':
                label: i18n
              'light':
                label: i18n
              'dark':
                label: i18n
