Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Ahorn.FriendlyCaptcha:Captcha':
            superTypes:
              - 'Neos.Form:FormElement'
            renderingOptions:
              templatePathPattern: 'resource://Ahorn.FriendlyCaptcha/Private/Form/Captcha.html'
              validationErrorTranslationPackage: Ahorn.FriendlyCaptcha
            implementationClassName: Ahorn\FriendlyCaptcha\FormElements\Captcha
  Neos:
    fusion:
      autoInclude:
        'Ahorn.FriendlyCaptcha': true
    userInterface:
      translation:
        autoInclude:
          'Ahorn.FriendlyCaptcha':
            - 'NodeTypes/*'

Ahorn:
  FriendlyCaptcha:
    siteKey: 'add-your-site-key'
    apiKey: 'add-your-api-key'
    language: 'de'
    startVerification: 'auto'
    apiEndpoint: 'global'
    theme: 'auto'
    cert: 'default'